---
- name: Apt-get update before installing
  apt: update_cache=yes cache_valid_time=3600

- name: Install Essential Packages
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - python-pycurl

- name: Install Git
  apt: pkg=git-core state=present
