---
- name: Deploys the whole software stack for a CakePHP application
  hosts: development
  user: vagrant
  sudo: yes

  vars_prompt:

  #CakePHP version
  - name: "cakephp_version"
    prompt: "What version of CakePHP do you want to deploy? (2 or 3)?"
    default: "3"

  roles:
    - system
    - php
    - bennojoy.nginx
    #Database engines
    - { role: percona }
    - { role: postgresql }
    #Database management tools
    - { role: phpmyadmin }
    - { role: phppgadmin }
    #Key value stores
    - { role: redis }
    - { role: memcached }
    #CakePHP
    - { role: cakephp2, when: cakephp_version == '2' }
    - { role: cakephp3, when: cakephp_version == '3' }

